#!/bin/bash
set -e
if [ "$DEBUG" ]; then set -x; fi

# Determine script directory and source libraries
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
source "${SCRIPT_DIR}/lib/ui.sh"

msg_header "OroDC Project Initialization"
msg_info ""

# Check if .env.orodc already exists
if [[ -f ".env.orodc" ]]; then
  msg_warning ".env.orodc already exists in this directory"
  if ! confirm_yes_no "Overwrite existing configuration?"; then
    msg_info "Initialization cancelled"
    exit 0
  fi
  
  # Backup existing file
  BACKUP_FILE=".env.orodc.backup.$(date +%Y%m%d_%H%M%S)"
  cp .env.orodc "$BACKUP_FILE"
  msg_info "Backed up existing configuration to: $BACKUP_FILE"
fi

# Detect project name from directory
DC_ORO_NAME=$(basename "$(pwd)")
msg_info "Project name: $DC_ORO_NAME"
msg_info ""

# PHP Version Selection
msg_info "Select PHP version:"
PHP_VERSION=$(prompt_selector "PHP version (default: 8.4): " "8.4" "8.2" "8.3" "8.4")

# Node Version Selection  
msg_info "Select Node.js version:"
NODE_VERSION=$(prompt_selector "Node.js version (default: 22): " "22" "20" "22" "23")

# Database Selection
msg_info "Select database:"
DATABASE=$(prompt_selector "Database (default: PostgreSQL): " "pgsql" "pgsql:PostgreSQL" "mysql:MySQL/MariaDB")

# Extract database schema
if [[ "$DATABASE" == *":"* ]]; then
  DB_SCHEMA="${DATABASE%%:*}"
else
  DB_SCHEMA="$DATABASE"
fi

# Set database version based on schema
if [[ "$DB_SCHEMA" == "pgsql" ]]; then
  DB_VERSION="17.4"
  DB_IMAGE="ghcr.io/digitalspacestdio/orodc-pgsql:17.4"
else
  DB_VERSION="10.11"
  DB_IMAGE="mariadb:10.11"
fi

# Search Engine Selection
msg_info "Select search engine:"
SEARCH=$(prompt_selector "Search engine (default: Elasticsearch): " "Elasticsearch" "Elasticsearch" "OpenSearch")

if [[ "$SEARCH" == "Elasticsearch" ]]; then
  SEARCH_VERSION="8.15.0"
  SEARCH_IMAGE="docker.elastic.co/elasticsearch/elasticsearch:8.15.0"
else
  SEARCH_VERSION="2.11.1"
  SEARCH_IMAGE="opensearchproject/opensearch:2.11.1"
fi

# Generate .env.orodc
msg_info ""
msg_info "Creating .env.orodc..."

cat > .env.orodc << EOF
# OroDC Configuration
# Generated by 'orodc init' on $(date)

# PHP Configuration
DC_ORO_PHP_VERSION=${PHP_VERSION}
DC_ORO_NODE_VERSION=${NODE_VERSION}
DC_ORO_PHP_IMAGE=ghcr.io/digitalspacestdio/orodc-php-node-symfony:${PHP_VERSION}-node${NODE_VERSION}-composer2-alpine

# Database Configuration
DC_ORO_DATABASE_SCHEMA=${DB_SCHEMA}
DC_ORO_DATABASE_VERSION=${DB_VERSION}
DC_ORO_DATABASE_IMAGE=${DB_IMAGE}

# Search Engine Configuration
DC_ORO_SEARCH_ENGINE=${SEARCH}
DC_ORO_SEARCH_VERSION=${SEARCH_VERSION}
DC_ORO_SEARCH_IMAGE=${SEARCH_IMAGE}

# Cache Configuration
DC_ORO_CACHE_ENGINE=Redis
DC_ORO_CACHE_VERSION=7.4
DC_ORO_CACHE_IMAGE=redis:7.4-alpine

# RabbitMQ Configuration
DC_ORO_RABBITMQ_VERSION=3.13
DC_ORO_RABBITMQ_IMAGE=rabbitmq:3.13-management-alpine

# Message Queue Configuration (default: DBAL for Community Oro)
DC_ORO_MQ_URI=dbal:

# Mailer Configuration
ORO_MAILER_DRIVER=sendmail
ORO_MAILER_HOST=
ORO_MAILER_PORT=
# ORO_MAILER_ENCRYPTION defaults to 'tls' (port 465) if not set
ORO_MAILER_USER=
ORO_MAILER_PASSWORD=

EOF

msg_ok "Created .env.orodc"
msg_info ""
msg_header "Project Initialized!"
msg_info ""
msg_info "Configuration:"
msg_info "  Project:     ${DC_ORO_NAME}"
msg_info "  PHP:         ${PHP_VERSION}"
msg_info "  Node.js:     ${NODE_VERSION}"
msg_info "  Database:    ${DB_SCHEMA} ${DB_VERSION}"
msg_info "  Search:      ${SEARCH} ${SEARCH_VERSION}"
msg_info ""
msg_info "Next steps:"
msg_info "  1. Start services:    orodc start"
msg_info "  2. Install ORO:       orodc install"
msg_info "  3. Access via proxy:  orodc proxy up -d"
msg_info ""
